---
#paths
folder_path: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/TEASER/TeaserOut/TEA_scenarios"
folder_modelica_path: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/TEASER/TeaserOut/modelica"
weather_path: ""
modelica_info: ""